@startuml
object "~#ti: TimeInterval" as ti1 {
}
object "~#tp1: TimePoint" as tp11 {
	hour = 12
	min = 15
}
object "~#tp2: TimePoint" as tp21 {
	hour = 14
	min = 0
}
ti1 --> tp11: start
ti1 --> tp21: end

object "~#ti: TimeInterval" as ti2 {
}
object "~#tp1: TimePoint" as tp12 {
	hour = 14
	min = 15
}
object "~#tp2: TimePoint" as tp22 {
	hour = 16
	min = 0
}
ti2 --> tp12: start
ti2 --> tp22: end

ti1 ..> ti2: setStartHour(14)

object "~#ti: TimeInterval" as ti3 {
}
object "~#tp1: TimePoint" as tp13 {
	hour = 14
	min = 00
}
object "~#tp2: TimePoint" as tp23 {
	hour = 15
	min = 45
}
ti3 --> tp13: start
ti3 --> tp23: end

ti2 ..> ti3: setStartMinutes(0)
@enduml
