@startuml
object "~#p2: Person2" as p21 {
	fullName = null
}
object "~#p2: Person2" as p22 {
	fullName = "Hallvard Trætteberg"
}
p21 ..> p22: setFullName("Hallvard Trætteberg");
p22 ..> p22: getGivenName() + " " + getFamilyName() == getFullName();
@enduml
